export const MOCK_CITIES = [
  {
    id: 'hanoi',
    name: 'Hà Nội',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    current: {
      temp: 31,
      feelsLike: 35,
      condition: 'partly-cloudy',
      conditionText: 'Có mây, oi bức',
      humidity: 78,
      windSpeed: 14,
      uvIndex: 8,
      uvText: 'Rất cao',
      pressure: 1008,
      visibility: 9,
      airQuality: 'Trung bình (AQI 82)',
      sunrise: '05:35',
      sunset: '18:28',
    },
    hourly: [
      { time: 'Bây giờ', temp: 31, condition: 'partly-cloudy', rainChance: 20 },
      { time: '18:00', temp: 30, condition: 'partly-cloudy', rainChance: 25 },
      { time: '20:00', temp: 28, condition: 'cloudy', rainChance: 30 },
      { time: '22:00', temp: 27, condition: 'rainy', rainChance: 60 },
      { time: '00:00', temp: 26, condition: 'rainy', rainChance: 70 },
      { time: '03:00', temp: 25, condition: 'thunderstorm', rainChance: 80 },
      { time: '06:00', temp: 26, condition: 'partly-cloudy', rainChance: 20 },
      { time: '09:00', temp: 29, condition: 'sunny', rainChance: 10 },
    ],
    forecast: [
      {
        day: 'Hôm nay',
        date: '17/08',
        tempMax: 33,
        tempMin: 26,
        condition: 'partly-cloudy',
        conditionText: 'Nắng gián đoạn',
        humidity: 78,
        windSpeed: 14,
        rainChance: 30,
      },
      {
        day: 'Thứ Ba',
        date: '18/08',
        tempMax: 32,
        tempMin: 25,
        condition: 'thunderstorm',
        conditionText: 'Mưa rào & dông rải rác',
        humidity: 85,
        windSpeed: 18,
        rainChance: 75,
      },
      {
        day: 'Thứ Tư',
        date: '19/08',
        tempMax: 34,
        tempMin: 27,
        condition: 'sunny',
        conditionText: 'Trời nắng nóng',
        humidity: 68,
        windSpeed: 12,
        rainChance: 10,
      },
      {
        day: 'Thứ Năm',
        date: '20/08',
        tempMax: 35,
        tempMin: 28,
        condition: 'sunny',
        conditionText: 'Nắng gắt cả ngày',
        humidity: 65,
        windSpeed: 11,
        rainChance: 5,
      },
      {
        day: 'Thứ Sáu',
        date: '21/08',
        tempMax: 30,
        tempMin: 24,
        condition: 'rainy',
        conditionText: 'Mưa rào hạ nhiệt',
        humidity: 82,
        windSpeed: 16,
        rainChance: 80,
      },
    ],
  },
  {
    id: 'hcm',
    name: 'TP. Hồ Chí Minh',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    current: {
      temp: 33,
      feelsLike: 38,
      condition: 'sunny',
      conditionText: 'Trời nắng, có mây',
      humidity: 72,
      windSpeed: 16,
      uvIndex: 10,
      uvText: 'Cực độ',
      pressure: 1010,
      visibility: 10,
      airQuality: 'Tốt (AQI 45)',
      sunrise: '05:42',
      sunset: '18:15',
    },
    hourly: [
      { time: 'Bây giờ', temp: 33, condition: 'sunny', rainChance: 10 },
      { time: '18:00', temp: 31, condition: 'partly-cloudy', rainChance: 15 },
      { time: '20:00', temp: 29, condition: 'cloudy', rainChance: 20 },
      { time: '22:00', temp: 28, condition: 'cloudy', rainChance: 20 },
      { time: '00:00', temp: 27, condition: 'partly-cloudy', rainChance: 10 },
      { time: '03:00', temp: 26, condition: 'partly-cloudy', rainChance: 10 },
      { time: '06:00', temp: 27, condition: 'sunny', rainChance: 5 },
      { time: '09:00', temp: 31, condition: 'sunny', rainChance: 10 },
    ],
    forecast: [
      {
        day: 'Hôm nay',
        date: '17/08',
        tempMax: 34,
        tempMin: 26,
        condition: 'sunny',
        conditionText: 'Nắng ban ngày, dịu về tối',
        humidity: 72,
        windSpeed: 16,
        rainChance: 20,
      },
      {
        day: 'Thứ Ba',
        date: '18/08',
        tempMax: 33,
        tempMin: 26,
        condition: 'rainy',
        conditionText: 'Mưa rào buổi chiều',
        humidity: 80,
        windSpeed: 15,
        rainChance: 65,
      },
      {
        day: 'Thứ Tư',
        date: '19/08',
        tempMax: 32,
        tempMin: 25,
        condition: 'thunderstorm',
        conditionText: 'Dông sét rải rác',
        humidity: 84,
        windSpeed: 20,
        rainChance: 85,
      },
      {
        day: 'Thứ Năm',
        date: '20/08',
        tempMax: 34,
        tempMin: 26,
        condition: 'partly-cloudy',
        conditionText: 'Trời hửng nắng',
        humidity: 74,
        windSpeed: 13,
        rainChance: 30,
      },
      {
        day: 'Thứ Sáu',
        date: '21/08',
        tempMax: 33,
        tempMin: 25,
        condition: 'partly-cloudy',
        conditionText: 'Thời tiết ôn hòa',
        humidity: 70,
        windSpeed: 14,
        rainChance: 25,
      },
    ],
  },
  {
    id: 'danang',
    name: 'Đà Nẵng',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    current: {
      temp: 29,
      feelsLike: 32,
      condition: 'rainy',
      conditionText: 'Mưa rào nhẹ',
      humidity: 86,
      windSpeed: 22,
      uvIndex: 4,
      uvText: 'Trung bình',
      pressure: 1012,
      visibility: 8,
      airQuality: 'Rất tốt (AQI 25)',
      sunrise: '05:33',
      sunset: '18:18',
    },
    hourly: [
      { time: 'Bây giờ', temp: 29, condition: 'rainy', rainChance: 70 },
      { time: '18:00', temp: 28, condition: 'rainy', rainChance: 65 },
      { time: '20:00', temp: 27, condition: 'partly-cloudy', rainChance: 40 },
      { time: '22:00', temp: 26, condition: 'cloudy', rainChance: 30 },
      { time: '00:00', temp: 25, condition: 'cloudy', rainChance: 20 },
      { time: '03:00', temp: 25, condition: 'partly-cloudy', rainChance: 20 },
      { time: '06:00', temp: 26, condition: 'sunny', rainChance: 15 },
      { time: '09:00', temp: 28, condition: 'sunny', rainChance: 10 },
    ],
    forecast: [
      {
        day: 'Hôm nay',
        date: '17/08',
        tempMax: 30,
        tempMin: 25,
        condition: 'rainy',
        conditionText: 'Mưa rải rác ven biển',
        humidity: 86,
        windSpeed: 22,
        rainChance: 70,
      },
      {
        day: 'Thứ Ba',
        date: '18/08',
        tempMax: 31,
        tempMin: 26,
        condition: 'partly-cloudy',
        conditionText: 'Trời tạnh, có mây',
        humidity: 78,
        windSpeed: 18,
        rainChance: 35,
      },
      {
        day: 'Thứ Tư',
        date: '19/08',
        tempMax: 33,
        tempMin: 27,
        condition: 'sunny',
        conditionText: 'Nắng đẹp cả ngày',
        humidity: 68,
        windSpeed: 14,
        rainChance: 15,
      },
      {
        day: 'Thứ Năm',
        date: '20/08',
        tempMax: 34,
        tempMin: 27,
        condition: 'sunny',
        conditionText: 'Nắng nhiều, gió mát',
        humidity: 66,
        windSpeed: 15,
        rainChance: 10,
      },
      {
        day: 'Thứ Sáu',
        date: '21/08',
        tempMax: 32,
        tempMin: 26,
        condition: 'partly-cloudy',
        conditionText: 'Có mây dông chiều tối',
        humidity: 74,
        windSpeed: 17,
        rainChance: 45,
      },
    ],
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Nhật Bản',
    region: 'Đông Á',
    current: {
      temp: 24,
      feelsLike: 24,
      condition: 'cloudy',
      conditionText: 'Nhiều mây, gió nhẹ',
      humidity: 60,
      windSpeed: 18,
      uvIndex: 5,
      uvText: 'Trung bình',
      pressure: 1016,
      visibility: 10,
      airQuality: 'Rất tốt (AQI 18)',
      sunrise: '05:01',
      sunset: '18:31',
    },
    hourly: [
      { time: 'Bây giờ', temp: 24, condition: 'cloudy', rainChance: 15 },
      { time: '18:00', temp: 23, condition: 'cloudy', rainChance: 20 },
      { time: '20:00', temp: 21, condition: 'partly-cloudy', rainChance: 10 },
      { time: '22:00', temp: 20, condition: 'partly-cloudy', rainChance: 5 },
      { time: '00:00', temp: 19, condition: 'sunny', rainChance: 0 },
      { time: '03:00', temp: 18, condition: 'sunny', rainChance: 0 },
      { time: '06:00', temp: 20, condition: 'sunny', rainChance: 0 },
      { time: '09:00', temp: 23, condition: 'sunny', rainChance: 5 },
    ],
    forecast: [
      {
        day: 'Hôm nay',
        date: '17/08',
        tempMax: 26,
        tempMin: 19,
        condition: 'cloudy',
        conditionText: 'Nhiều mây bao phủ',
        humidity: 60,
        windSpeed: 18,
        rainChance: 20,
      },
      {
        day: 'Thứ Ba',
        date: '18/08',
        tempMax: 27,
        tempMin: 18,
        condition: 'sunny',
        conditionText: 'Trời trong xanh',
        humidity: 52,
        windSpeed: 14,
        rainChance: 5,
      },
      {
        day: 'Thứ Tư',
        date: '19/08',
        tempMax: 28,
        tempMin: 20,
        condition: 'sunny',
        conditionText: 'Nắng ấm áp',
        humidity: 55,
        windSpeed: 12,
        rainChance: 10,
      },
      {
        day: 'Thứ Năm',
        date: '20/08',
        tempMax: 25,
        tempMin: 19,
        condition: 'rainy',
        conditionText: 'Mưa rào nhẹ',
        humidity: 75,
        windSpeed: 20,
        rainChance: 65,
      },
      {
        day: 'Thứ Sáu',
        date: '21/08',
        tempMax: 26,
        tempMin: 18,
        condition: 'partly-cloudy',
        conditionText: 'Trời quang mây tạnh',
        humidity: 58,
        windSpeed: 16,
        rainChance: 20,
      },
    ],
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'Pháp',
    region: 'Châu Âu',
    current: {
      temp: 21,
      feelsLike: 20,
      condition: 'partly-cloudy',
      conditionText: 'Nắng nhẹ, gió mát',
      humidity: 55,
      windSpeed: 12,
      uvIndex: 4,
      uvText: 'Trung bình',
      pressure: 1018,
      visibility: 10,
      airQuality: 'Tốt (AQI 32)',
      sunrise: '06:40',
      sunset: '21:05',
    },
    hourly: [
      { time: 'Bây giờ', temp: 21, condition: 'partly-cloudy', rainChance: 10 },
      { time: '18:00', temp: 22, condition: 'sunny', rainChance: 5 },
      { time: '20:00', temp: 20, condition: 'sunny', rainChance: 0 },
      { time: '22:00', temp: 17, condition: 'partly-cloudy', rainChance: 0 },
      { time: '00:00', temp: 15, condition: 'partly-cloudy', rainChance: 5 },
      { time: '03:00', temp: 13, condition: 'cloudy', rainChance: 10 },
      { time: '06:00', temp: 14, condition: 'cloudy', rainChance: 15 },
      { time: '09:00', temp: 18, condition: 'partly-cloudy', rainChance: 10 },
    ],
    forecast: [
      {
        day: 'Hôm nay',
        date: '17/08',
        tempMax: 23,
        tempMin: 14,
        condition: 'partly-cloudy',
        conditionText: 'Thời tiết mùa thu mát mẻ',
        humidity: 55,
        windSpeed: 12,
        rainChance: 15,
      },
      {
        day: 'Thứ Ba',
        date: '18/08',
        tempMax: 24,
        tempMin: 15,
        condition: 'sunny',
        conditionText: 'Nắng trong lành',
        humidity: 50,
        windSpeed: 10,
        rainChance: 5,
      },
      {
        day: 'Thứ Tư',
        date: '19/08',
        tempMax: 22,
        tempMin: 13,
        condition: 'cloudy',
        conditionText: 'Mây che phủ',
        humidity: 62,
        windSpeed: 15,
        rainChance: 25,
      },
      {
        day: 'Thứ Năm',
        date: '20/08',
        tempMax: 20,
        tempMin: 12,
        condition: 'rainy',
        conditionText: 'Mưa phùn rải rác',
        humidity: 78,
        windSpeed: 18,
        rainChance: 70,
      },
      {
        day: 'Thứ Sáu',
        date: '21/08',
        tempMax: 23,
        tempMin: 14,
        condition: 'sunny',
        conditionText: 'Nắng đẹp trở lại',
        humidity: 52,
        windSpeed: 11,
        rainChance: 10,
      },
    ],
  },
  {
    id: 'newyork',
    name: 'New York',
    country: 'Hoa Kỳ',
    region: 'Bắc Mỹ',
    current: {
      temp: 26,
      feelsLike: 27,
      condition: 'sunny',
      conditionText: 'Trời quang, nắng đẹp',
      humidity: 58,
      windSpeed: 15,
      uvIndex: 7,
      uvText: 'Cao',
      pressure: 1015,
      visibility: 10,
      airQuality: 'Tốt (AQI 38)',
      sunrise: '06:10',
      sunset: '19:54',
    },
    hourly: [
      { time: 'Bây giờ', temp: 26, condition: 'sunny', rainChance: 5 },
      { time: '18:00', temp: 27, condition: 'sunny', rainChance: 5 },
      { time: '20:00', temp: 24, condition: 'partly-cloudy', rainChance: 10 },
      { time: '22:00', temp: 22, condition: 'partly-cloudy', rainChance: 15 },
      { time: '00:00', temp: 20, condition: 'cloudy', rainChance: 20 },
      { time: '03:00', temp: 19, condition: 'cloudy', rainChance: 20 },
      { time: '06:00', temp: 21, condition: 'partly-cloudy', rainChance: 10 },
      { time: '09:00', temp: 24, condition: 'sunny', rainChance: 5 },
    ],
    forecast: [
      {
        day: 'Hôm nay',
        date: '17/08',
        tempMax: 28,
        tempMin: 20,
        condition: 'sunny',
        conditionText: 'Trời trong xanh',
        humidity: 58,
        windSpeed: 15,
        rainChance: 10,
      },
      {
        day: 'Thứ Ba',
        date: '18/08',
        tempMax: 29,
        tempMin: 21,
        condition: 'partly-cloudy',
        conditionText: 'Nắng có mây',
        humidity: 62,
        windSpeed: 16,
        rainChance: 20,
      },
      {
        day: 'Thứ Tư',
        date: '19/08',
        tempMax: 27,
        tempMin: 19,
        condition: 'thunderstorm',
        conditionText: 'Dông bão chiều tối',
        humidity: 78,
        windSpeed: 24,
        rainChance: 80,
      },
      {
        day: 'Thứ Năm',
        date: '20/08',
        tempMax: 25,
        tempMin: 18,
        condition: 'partly-cloudy',
        conditionText: 'Không khí trong lành',
        humidity: 54,
        windSpeed: 14,
        rainChance: 15,
      },
      {
        day: 'Thứ Sáu',
        date: '21/08',
        tempMax: 27,
        tempMin: 19,
        condition: 'sunny',
        conditionText: 'Nắng rực rỡ',
        humidity: 50,
        windSpeed: 12,
        rainChance: 5,
      },
    ],
  },
  {
    id: 'london',
    name: 'London',
    country: 'Vương quốc Anh',
    region: 'Châu Âu',
    current: {
      temp: 18,
      feelsLike: 17,
      condition: 'rainy',
      conditionText: 'Mưa phùn đặc trưng',
      humidity: 88,
      windSpeed: 20,
      uvIndex: 3,
      uvText: 'Thấp',
      pressure: 1011,
      visibility: 7,
      airQuality: 'Rất tốt (AQI 22)',
      sunrise: '05:48',
      sunset: '20:20',
    },
    hourly: [
      { time: 'Bây giờ', temp: 18, condition: 'rainy', rainChance: 85 },
      { time: '18:00', temp: 17, condition: 'rainy', rainChance: 75 },
      { time: '20:00', temp: 16, condition: 'cloudy', rainChance: 40 },
      { time: '22:00', temp: 15, condition: 'cloudy', rainChance: 30 },
      { time: '00:00', temp: 14, condition: 'partly-cloudy', rainChance: 20 },
      { time: '03:00', temp: 13, condition: 'foggy', rainChance: 25 },
      { time: '06:00', temp: 14, condition: 'foggy', rainChance: 30 },
      { time: '09:00', temp: 16, condition: 'partly-cloudy', rainChance: 20 },
    ],
    forecast: [
      {
        day: 'Hôm nay',
        date: '17/08',
        tempMax: 19,
        tempMin: 14,
        condition: 'rainy',
        conditionText: 'Mưa phùn ẩm ướt',
        humidity: 88,
        windSpeed: 20,
        rainChance: 85,
      },
      {
        day: 'Thứ Ba',
        date: '18/08',
        tempMax: 20,
        tempMin: 13,
        condition: 'cloudy',
        conditionText: 'Trời âm u',
        humidity: 78,
        windSpeed: 17,
        rainChance: 40,
      },
      {
        day: 'Thứ Tư',
        date: '19/08',
        tempMax: 22,
        tempMin: 14,
        condition: 'partly-cloudy',
        conditionText: 'Hửng nắng nhẹ',
        humidity: 65,
        windSpeed: 14,
        rainChance: 20,
      },
      {
        day: 'Thứ Năm',
        date: '20/08',
        tempMax: 21,
        tempMin: 15,
        condition: 'sunny',
        conditionText: 'Nắng ấm',
        humidity: 60,
        windSpeed: 12,
        rainChance: 15,
      },
      {
        day: 'Thứ Sáu',
        date: '21/08',
        tempMax: 19,
        tempMin: 13,
        condition: 'rainy',
        conditionText: 'Mưa rào trở lại',
        humidity: 82,
        windSpeed: 22,
        rainChance: 75,
      },
    ],
  },
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'Hàn Quốc',
    region: 'Đông Á',
    current: {
      temp: 27,
      feelsLike: 29,
      condition: 'sunny',
      conditionText: 'Nắng ráo, gió nhẹ',
      humidity: 62,
      windSpeed: 11,
      uvIndex: 7,
      uvText: 'Cao',
      pressure: 1013,
      visibility: 10,
      airQuality: 'Trung bình (AQI 65)',
      sunrise: '05:48',
      sunset: '19:22',
    },
    hourly: [
      { time: 'Bây giờ', temp: 27, condition: 'sunny', rainChance: 5 },
      { time: '18:00', temp: 26, condition: 'sunny', rainChance: 5 },
      { time: '20:00', temp: 24, condition: 'partly-cloudy', rainChance: 10 },
      { time: '22:00', temp: 22, condition: 'partly-cloudy', rainChance: 10 },
      { time: '00:00', temp: 21, condition: 'partly-cloudy', rainChance: 5 },
      { time: '03:00', temp: 20, condition: 'sunny', rainChance: 0 },
      { time: '06:00', temp: 22, condition: 'sunny', rainChance: 0 },
      { time: '09:00', temp: 25, condition: 'sunny', rainChance: 5 },
    ],
    forecast: [
      {
        day: 'Hôm nay',
        date: '17/08',
        tempMax: 29,
        tempMin: 20,
        condition: 'sunny',
        conditionText: 'Nắng chan hòa',
        humidity: 62,
        windSpeed: 11,
        rainChance: 10,
      },
      {
        day: 'Thứ Ba',
        date: '18/08',
        tempMax: 28,
        tempMin: 21,
        condition: 'partly-cloudy',
        conditionText: 'Mây nhẹ chiều',
        humidity: 66,
        windSpeed: 13,
        rainChance: 25,
      },
      {
        day: 'Thứ Tư',
        date: '19/08',
        tempMax: 26,
        tempMin: 19,
        condition: 'rainy',
        conditionText: 'Mưa rào mùa hè',
        humidity: 82,
        windSpeed: 18,
        rainChance: 70,
      },
      {
        day: 'Thứ Năm',
        date: '20/08',
        tempMax: 27,
        tempMin: 19,
        condition: 'partly-cloudy',
        conditionText: 'Thời tiết dễ chịu',
        humidity: 64,
        windSpeed: 12,
        rainChance: 20,
      },
      {
        day: 'Thứ Sáu',
        date: '21/08',
        tempMax: 29,
        tempMin: 20,
        condition: 'sunny',
        conditionText: 'Nắng đẹp cuối tuần',
        humidity: 58,
        windSpeed: 10,
        rainChance: 10,
      },
    ],
  },
]
